// <auto-generated />
namespace Backend_Final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateSeats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateSeats));
        
        string IMigrationMetadata.Id
        {
            get { return "202109101341591_update Seats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
